# Generated by Django 4.1.7 on 2023-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
