# Generated by Django 4.1.7 on 2023-03-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galleries", "0002_gallery_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="folder",
            field=models.CharField(default="", max_length=33),
        ),
    ]
